"""create initial tables

Revision ID: 407f3b64868a
Revises:
Create Date: 2026-09-02 14:27:49.362680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '407f3b64868a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfers',
    sa.Column('transfer_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('transfer_id')
    )
    op.create_table('user_accounts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('user_name', sa.String(length=30), nullable=False),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.CheckConstraint('balance >= 0.00', name='check_non_negative_balance'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('account_entries',
    sa.Column('entry_id', sa.Uuid(), nullable=False),
    sa.Column('transfer_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('entry_type', sa.Enum('C', 'D', name='entry_type_enum'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('amount > 0.00', name='check_positive_amount'),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.transfer_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.user_id'], ),
    sa.PrimaryKeyConstraint('entry_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_entries')
    op.drop_table('user_accounts')
    op.drop_table('transfers')
    sa.Enum(name="entry_type_enum").drop(
        op.get_bind(),
        checkfirst=True,
    )
    # ### end Alembic commands ###
